services:
  - type: web
    name: riccoai-1
    env: python
    buildCommand: |
      echo "Current location:"
      pwd
      echo "Directory contents:"
      ls -la
      echo "Backend directory contents:"
      ls -la src/backend/
      echo "Installing requirements..."
      python -m pip install -r src/backend/requirements.txt
    startCommand: cd src/backend && PYTHONPATH=$PYTHONPATH:.. uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: OPENAI_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_ENV
        sync: false
      - key: UPSTASH_REDIS_URL
        sync: false
      - key: UPSTASH_REDIS_TOKEN
        sync: false
      - key: MAKE_WEBHOOK_URL
        sync: false
    assets:
      - path: docs