services:
  - type: web
    name: riccoai-1
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: PYTHONPATH=$PYTHONPATH:$(pwd) python -m uvicorn src.backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: OPENAI_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_ENV
        sync: false
      - key: UPSTASH_REDIS_URL
        sync: false
      - key: UPSTASH_REDIS_TOKEN
        sync: false
      - key: MAKE_WEBHOOK_URL
        sync: false
    assets:
      - path: docs